# Generated by Django 5.1.4 on 2024-12-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_augment_image_remote_sensing_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="augment_image",
            name="img_path",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="增强结果路径"
            ),
        ),
        migrations.AlterField(
            model_name="remote_sensing_image",
            name="img_path",
            field=models.ImageField(
                blank=True,
                max_length=128,
                null=True,
                upload_to="",
                verbose_name="原始图像路径",
            ),
        ),
        migrations.AlterField(
            model_name="segmentation_image",
            name="img_path",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="分割结果路径"
            ),
        ),
    ]
